### ISSUE TITLE
Seed Phrase Verification

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#10]
As a user I would like to be able to verify my seed phrase when I first start up my wallet to ensure that I have correctly written down my seed phrase.

Criteria:
- [ ] Upon initial startup the wallet will show the seed phrase, following the seed phrase list the user must verify they saved the words by inputting them in order.
- [ ] This work flow only happens once but if the user decides to skip verification they are reminded to verify when they open the app until they do.

**Comment by gmale** [comment]
Complete.
