### ISSUE TITLE
Application Log Long Press Broken

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#104]
On some devices, long pressing on `See Application Logs` does not open the share drawer. Reach out to mineZcash on discord for more details.

**Comment by gmale** [comment]
This needs to be retested now that #181 has been merged. After a new build is out, I'll reach out to MineZcash and see if this improves things for him.

**Comment by gmale** [comment]
This should be fixed. closing.
can be re-opened if it's still a problem.
