### ISSUE TITLE
Implement new send flow without t-address capabilities

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#113]
Implement the new send flow without adding t-address capabilities. This includes revising the send screen and minor revisions to the confirmation screen.

@geffenz Please attach those designs here.

Acceptance Criteria:
- [ ] Design accepted by Geffen re: originals

**Comment by gmale** [comment]
Update: should probably sit down with @geffenz and review this to find any departures from designs that need to be changed.

**Comment by geffenz** [comment]
Looks great, very small changes.

- [ ] Send button should be disabled, but please keep the feedback (add to address, etc) if a user presses anyway.
- [ ] (if possible) can we get a few pixels between fields and the directions/char count. They are crowding the line.
- [ ] Add matching bottom margin to equal the top margin of the form (more room before ON CLIPBOARD, etc)
- [ ] Scan QR shouldn't be able to switch to your address anymore (opposite is true on your address screen)
- [ ] Can we have Unknown title check against your addresses and change to 'Your Address'. 
- [ ] See details has breadcrumb history so back doesn't go to homescreen (it goes to a new send) - a bit confusing.
- [ ] Not enough ZEC alert is too long and therefore unreadble. I think a modal that alerts and uto sends you back might be better.
- [ ] When sent back the < button doesn't clear amount.
- [ ] When sending to yourself history only shows send not receive.

WISHLIST notes for Geffen
- [ ] Animation after hitting send
- [ ] More contrast/animation after hitting cancel

**Comment by gmale** [comment]
Note: slight improvement to create TX immediately, even before the bio authentication (but don't send)

**Comment by gmale** [comment]
Update @lindanlee : synced with Geffen and the next step is to implement a few of these things before the next release, meaning, I'd expect to finally close this ticket at the end of the sprint and just spin out another ticket for any remaining work.

**Comment by gmale** [comment]
> Not enough ZEC alert is too long and therefore unreadble. I think a modal that alerts and auto sends you back might be better.

Rationale: for this one, I opted to extend the message display time rather than add a modal because this is weird UX and I don't want to add extra logic or draw attention to it. Instead, we can hopefully fix it later by allowing edit on this screen.

**Comment by gmale** [comment]
This is done. I just need to spin everything else out into tickets.

**Comment by gmale** [comment]
@geffenz can you review this checklist and then maybe sync w/ me on any issues?
