### ISSUE TITLE
Add test vector tests for novacrypto.bip39

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet#119]
Write a test that has a hard-coded entropy byte array, expected mnemonic, and expected seed. Use `Mnemonics` to calculate the mnemonic and verify that it's as expected, then calculate the seed from the mnemonic and verify that it's as expected.

Get the expected values from a different implementation (e.g. the one iOS uses). This will make sure it's calculating the values correctly and will also make it easy to switch out `novacrypto.bip39` with something else if we ever have to since this test ensures compatibility.

**Comment by gmale** [comment]
Closing because Novacrypto has been removed (due to license issues) and replaced with our own implementation that does thorough testing as described here.
