### ISSUE TITLE
Remove (apparent) logging of characters typed

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet#128]
I think the following code applies to the big number pad in the app:

```
    private fun TextView.asKey(): TextView {
        val c = text[0]
        setOnClickListener {
            lifecycleScope.launch {
                twig("CHAR TYPED: $c")
                viewModel.onChar(c)
            }
        }
        return this
    }
```

We should remove the `twig("CHAR TYPED: $c")` line to avoid anyone thinking (at a glance) that the app logs everything the user types, and also so that values they type in aren't logged.

**Comment by nighthawk24** [comment]
@mandeepbhalothia is on this
