### ISSUE TITLE
Wallet History Icons and Colors Match TX Detail

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#142]
The new iconography and color palette for the revised tx detail screen should be bubbled up to the wallet history screen as well.

**Comment by geffenz** [comment]
Assigning to myself to make a clear design doc on these

**Comment by lindanlee** [comment]
The intent of the ticket was to get design ahead one sprint to be able to implement changes next sprint. We will consider this done (decided during a standup, all people present).

**Comment by gmale** [comment]
Feedback:
First, this is amazing and a fantastic style guide. I didn't find may issues with it other than colors. I think we have a few more grays than what is listed here and the primary text color is missing (white). I'm a little unclear on the differences in the yellows, particularly the bright where the bright yellow is used and when to use the 1st vs. 3rd yellow. Perhaps we should also label some of the colors that have an intended purpose, which might also help when referencing them.

Some suggested names:

primary
primary_dimmed
secondary (for all the blues used for shielded)
secondary_dimmed
accent
text_primary
text_secondary
error
primary_button_active
primary_button_pressed
primary_button_disabled
secondary_button_active
secondary_button_pressed
secondary_button_disabled

**Comment by gmale** [comment]
The color for disabled send `#7C5A00` appears to differ from the color for the "disabled" button `#FFB900` @ 40% opacity, which differs slightly from the primary app color in the color palette: `#FFB700`

For now, I will use `#7C5A00`.

**Comment by gmale** [comment]
@geffenz 
The color for disabled send `#7C5A00` appears to differ from the color for the "disabled" button `#FFB900` @ 40% opacity, which differs slightly from the primary app color in the color palette: `#FFB700`

For now, I will use `#7C5A00`.

**Comment by gmale** [comment]
@geffenz just noticed the "expand memo" icon (circle with arrows) is missing from the design guide.
