### ISSUE TITLE
Logging Settings

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#143]
As a user I would like to be able to build the Android app with logging and crash reporting on or off with a build flag. This will prevent users from submitting logs without their knowledge. The default build setting should be without logging.

Requirement:
- [ ] The wallet can be built with a logging or no-logging flag
- [ ] If remote logging is present, the user is made aware on launch. This should be dismissible

**Comment by gmale** [comment]
We've already gotten feedback that even just the _presence_ of the analytics SDKs makes some people apprehensive. If we continue to hear concerns in this area, then it might be worthwhile to reopen this issue and address the topic here, in the open.

Suggestion that was given:
You may want to put a build-time flag (or just completely remove that code for now) to avoid these concerns.

Perhaps we make a "dogfooding" build [variant](https://developer.android.com/studio/build/build-variants) that we only use for internal builds.

**Comment by gmale** [comment]
This topic has been further discussed as part of the (awesome) nighthawk release:
https://forum.zcashcommunity.com/t/announcing-nighthawk-wallet-for-zcash/36723/5

Concerns that were raised include:

> --- from @dontbevil:
> @joshs do you know what this is about?

> --- from @tromer:
> Calling the two analytics libraries is disabled in runtime, but I believe they are still linked in. That may be enough to trigger their (potentially nefarious) code, via initializers etc.

---
I gave a [detailed response](https://forum.zcashcommunity.com/t/announcing-nighthawk-wallet-for-zcash/36723/12) in that thread, which I would summarize as "it is behaving as intended and we can make it better, after the hackathon, but it might not be top priority, given the actual purpose of the app."
