### ISSUE TITLE
Feature Request: Support QR Scanning on devices without Google Play Services.

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#165]
Migrated issue https://github.com/zcash/zcash-android-wallet-sdk/issues/135 from the SDK, originally submitted by @BostonZcash :

-----

**What is the bug?**
In attempting to scan z-address QR codes (no URI or payment requests embedded), app does not recognize any such code (regardless of whitespace, etc.). Rather, it behaves as if no QR code is being presented.

**Additional context**
LineageOS 16.0 & ECC Wallet 1.0.0-alpha29. No Google Play Services (openGApps) have sullied this device.

**Solution**
I ran into the same issue on initial builds of adityapk00/zqwandroid, later corrected. As I recall, it was due to relying on a Google library to perform decoding/parsing, which is not included on base LineageOS images.

**Comment by gmale** [comment]
The QR Scanner is [separated out as its own module](https://github.com/zcash/zcash-android-wallet/blob/master/qrecycler/src/main/java/cash/z/android/qrecycler/QScanner.kt#L7) just in case the Firebase implementation becomes an issue:
```kotlin
interface QScanner {
    fun scanBarcode(callback: (Result<String>) -> Unit)
}
```

So this can be changed fairly easily. However, I'm pretty sure I've seen this run on non-play-store devices. Perhaps the barcode being scanned was not the proper format?

This seems to be one more use case in favor of https://github.com/zcash/zcash-android-wallet/issues/157 where it is helpful to give visual feedback during non-successful scans. 

@BostonZcash what happens when you scan this code (which is valid for mainnet):


![Screenshot_1592336921](https://user-images.githubusercontent.com/1699841/84821307-e6f04180-afe8-11ea-8ef1-78e4f1e83ab1.png)

**Comment by gmale** [comment]
Recently, there have been discussions about swapping out the existing Firebase camera and using zebra crossing, instead. I was going to make a github issue for that work but this issue already exists.

@herou once you comment on this issue, I'll be able to assign it to you [per the new access permissions rules](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users#:~:text=You%20can%20assign%20up%20to,%22Access%20permissions%20on%20GitHub.%22).
and @nighthawk24 will be able to make use of this change.

**Comment by herou** [comment]
@gmale assign this to me.

**Comment by gmale** [comment]
I believe this is probably the only thing that needs to change.
https://github.com/zcash/zcash-android-wallet/blob/master/app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt#L28-L51

**Comment by gmale** [comment]
Turns out many of the zxing libraries have gotten to be out-dated and are not well maintained but the zxing-core APIs are still used in a lot of places.

@nighthawk24 linked to the [barcode-kaiteki](https://github.com/kroegerama/barcode-kaiteki) library which is helpful because it takes a fairly modern approach using CameraX. Unfortunately, it is a little dated because it is still using [alpha APIs](https://github.com/kroegerama/barcode-kaiteki/blob/master/library/src/main/java/com/kroegerama/kaiteki/bcode/views/BarcodeView.kt#L113). 

Plus, it is heavy on UI and overlaps a lot of what we already have in place. So we can just follow a similar approach and use the [MultiFormatReader from zxing](https://github.com/kroegerama/barcode-kaiteki/blob/master/library/src/main/java/com/kroegerama/kaiteki/bcode/BarcodeAnalyzer.kt#L52).

## Recommended Approach
At a high level, here is my recommended approach:

1. update [zxing to 3.4.1](https://github.com/zcash/zcash-android-wallet/blob/4662bdc08e412cc32e2afb3e41c7756ef03e652a/buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt#L98) from 3.2.1
2. change the QRanalyzer to use the MultiFormatReader, rather than firebase
   - Essentially swap [this code in the wallet](https://github.com/zcash/zcash-android-wallet/blob/672dfc7d4787b02257d3cb83d466bc721f1c6bca/app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt#L27-L52) with [this code from the barcode-kaiteki library](https://github.com/kroegerama/barcode-kaiteki/blob/master/library/src/main/java/com/kroegerama/kaiteki/bcode/BarcodeAnalyzer.kt#L26-L57) with whatever minor tweaks are needed to get it to work.
   - Note: one such tweak would be that we can just create an instance of `MultiFormatReader` rather than passing it in to the Analyzer
3. Test it out and see if it works to scan QRs
4. Once that's working, THEN update the [cameraX dependencies](https://github.com/zcash/zcash-android-wallet/blob/672dfc7d4787b02257d3cb83d466bc721f1c6bca/buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt#L28-L31) to the latest version (I think `1.0.0-rc01`) and update any breaking API changes
5. Cleanup and delete all [firebase related code](https://github.com/zcash/zcash-android-wallet/blob/672dfc7d4787b02257d3cb83d466bc721f1c6bca/buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt#L61), including the [gms import](https://github.com/zcash/zcash-android-wallet/blob/672dfc7d4787b02257d3cb83d466bc721f1c6bca/build.gradle#L13).

**Comment by gmale** [comment]
completed by https://github.com/zcash/zcash-android-wallet/pull/232
