### ISSUE TITLE
send text field broken when backspacing

### ISSUE THREAD

**Issue by imichaelmiers** [zcash/zcash-android-wallet#169]
**Bug vs expected behavior**
If I paste in "zs1dc9e335zs5sp74lyrpj82mheza9y09wyjfywpyee45n4ucsc0shdqjdcrz3ajy7t0djwwn99lq7 is my mobile wallet" (because signal only lets you copy the whole message). I expect to be able to delete the later part. Pasting works. 

However, If i hit backspace 6 times , it then jumps to the front of the textbox.  This repeats again once I delete 6 more, then again on 2 more.
**Device (please complete the following information):**
 - Android Device: Pixel 3
 - Android Version:  Android 10, up to date as of  6:32 today. Last security patch  june 5.
* nighthawk wallet

**Comment by gmale** [comment]
Thanks, I'll try to reproduce this.

That is a vanilla system component and the editing is mostly controlled by the system. Perhaps I've set validation to run once the user stops typing and then when validation fails it moves the cursor? I'll have a look!
