### ISSUE TITLE
Enhancement: get the app to work on testnet

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#171]
Right now it compiles but fails on startup due to Firebase issues.

**Comment by gmale** [comment]
Probably a bigger thing because it's not just switching, it's making sure people don't get confused and it is very clear when the app is in "testnet mode". We could even do things in that mode like working with 1 confirmation.

This could become an epic.

**Comment by gmale** [comment]
Given that we have darksidewalletd, we prefer using that over using testnet. So this is lower priority.

**Comment by herou** [comment]
@gmale Assign it to me.

**Comment by herou** [comment]
@gmale I was able to install the testnetDebug build variant as shown in the pic:

![image](https://user-images.githubusercontent.com/13895430/106365112-9ccb8e80-6333-11eb-8452-dd00510562d0.png)

**Comment by gmale** [comment]
closed by #227
