### ISSUE TITLE
On some devices pressing the Application Log crashes the app

### ISSUE THREAD

**Issue by CrystalPony** [zcash/zcash-android-wallet#174]
Reproduced on Redmi Note 7

**Comment by gmale** [comment]
I've seen this but have hard a time reproducing it. My theory is that I fixed this, internally, but it resurfaced when attempting to strip all dogfooding features out of the repository. This should be investigated and corrected.

**Comment by CrystalPony** [comment]
I'll poke this since it's consistently reproducible for me.
