### ISSUE TITLE
Suggestion: add the ability to change the lightwalletd server

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#182]
As a user, I'd like to point to my local instance of lightwalletd running on the same network so that I can do more sensitive operations at home but retain the ability to use public servers for everything else.

**Comment by gmale** [comment]
credit: @ChileBob for the suggestion!

**Comment by gmale** [comment]
I'm guessing this would live as an option under the profile tab. Perhaps under a settings screen, if we have lots of things we want to configure.

**Comment by braddmiller** [comment]
I'm a big fan of this idea, going to add it to the product backlog for both platforms so we can prioritize in a near-future sprint.

**Comment by gmale** [comment]
Notes: this has been implemented in [nighthawk](https://github.com/nighthawk-apps/nighthawk-wallet-android/pull/5) using Android's built-in encrypted shared preferences. It also involves a restart of the main activity, which might be avoidable. Overall, though, this would be a great addition to collaborate on.

**Comment by nighthawk24** [comment]
@gmale thanks for the recognition! I'm happy to make a PR whenever this issue is prioritized!

**Comment by gmale** [comment]
@nighthawk24 Hey Adi, we just pulled this into our sprint. Let's sync (maybe on keybase) about doing a PR. It will be fun to collaborate!

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/8d3dfcab-eee4-4376-a4d5-fe313292d4f1) Setting ideas aggregated
