### ISSUE TITLE
Switch from "sent-from" to "reply-to"

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#183]
Per the Zcash Gardening Club request, we should standardize on memo formats. Using "Reply-To" is preferred over "sent-from" because the former underscores the idea that the given address is not necessarily the address that originated the transaction.

Credit @ChileBob for the suggestion.

**Comment by braddmiller** [comment]
@gmale I'm putting this on the backlog to make us compatible with all other wallets, there's more "standardization" work that needs to be done, but there's more to it than just the identifying tag so let's just make this change as an intermediate step to bring all the wallets closer together.
