### ISSUE TITLE
Research Spike: Background Sync

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#195]
Research on how to add background syncing to the Android wallet and create tickets for work. 

Time box: 2 hours

**Comment by nighthawk24** [comment]
Background syncing implementation can be kept optional to allow the user to decide & achieved by running a service. This feature will enable the implementation of notifications when the user receives ZEC too.

**Comment by gmale** [comment]
Added related ticket:
https://github.com/zcash/zcash-android-wallet-sdk/issues/160
