### ISSUE TITLE
Missing encryption libraries on older devices prevent app usage

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#196]
Devices such as the `Pixel 5X` and the `HTC One A9` running API 22 and 24, respectively, are unable to create or restore wallets due to the following error:

>SecretKeyFactory PBKDF2WithHmacSHA512 implementation not found

This means we cannot rely on the built in cryptographic functions for those devices and, instead, must fall back to a Java implementation. I previously used one but [removed it in this commit, in favor of the built-in Java version](https://github.com/zcash/kotlin-bip39/commit/ada0c1d2a9a39334ff5248cb9ca87e26d1a87974#diff-83ece269024ec635d7a56459c92d99ef). Apparently, that version isn't available everywhere.

The solution here is probably to do a better migration of that code to Kotlin from Java and have it audited. Then use that in cases where the device does not have the library available.

Meanwhile, we should at least put a better error message around this.

Note: [Related bugsnag event](https://app.bugsnag.com/electric-coin-company/ecc-wallet/errors/5f36100336a0970018aef303?filters%5Bevent.since%5D%5B0%5D=7d&filters%5Bapp.release_stage%5D%5B0%5D%5Bvalue%5D=production&filters%5Bapp.release_stage%5D%5B0%5D%5Btype%5D=eq&filters%5Bdevice.model%5D%5B0%5D=2PQ93&pivot_tab=event)

**Comment by gmale** [comment]
Update: @geffenz researched and confirmed that raising the minimum SDK to API 24 causes us to miss our objective of 90%+ of users. So we're going to have to fix this.

**Comment by geffenz** [comment]
Research: https://zcashco.atlassian.net/wiki/spaces/~528828256/pages/817594369/OS+Hardware+Minimums+Localization+for+Mobile+Wallets

**Comment by lindanlee** [comment]
Required work to finish off a team OKR!

**Comment by gmale** [comment]
Shows up in bugsnag as: https://app.bugsnag.com/electric-coin-company/ecc-wallet/errors/5f36100336a0970018aef303
