### ISSUE TITLE
Localization for Android

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-android-wallet#200]
As a developer, I'd like to work with the Android SDK and have all text in the app match the user's locale.

Criteria
For each supported language (English, Spanish, simplified Chinese, Russian):
- [x] Each screen in the app only contains words in that language
- [x] Layouts are not broken for the most common screen sizes
- [ ] (optional, prioritize all other localization first) number, date and time formats match the locale (this is deceptively complex for the number entry fields).

Implementation details
- [x] all text from all screens is pulled out of layout files and code and put into `strings.xml` for localization **[3 pts]**
- [ ] date/time formatters should be modified for proper localization support **[3 pts]**
- [ ] (optional, prioritize all other localization first) currency formatter should either support each locale or be consistent for all locales. The former probably takes a lot of effort and is prone to bugs. **[3 pts]**

**Comment by lindanlee** [comment]
Not yet started.

**Comment by gmale** [comment]
The words that we have have been pulled in but the down-side is that many screens don't have all their words captured and the words we have translated are not all present in the Android app.

Next step is to put out builds on Android with the translations.
