### ISSUE TITLE
Memos should be disabled when sending to a transparent address

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#206]
In the new Send flow, a user should not be able to input a memo if they're sending to a t-addr. Perhaps the field goes away and is replaced with something with the sentiment of:
> to add a memo, enter a shielded address

Update: merged with issue #212
Note that "reply-to" should also not be an option.

**Comment by gmale** [comment]
Example of existing send screen:


Example of valid Z-Address:
zs1vw3stxg9amj88mjn74q6y09l3v245tf6nmgknnetlegcu89q22raqvuuyf4elpnna6rsgwuu5fg

Example of valid T-Address:
t1coURaGEsTgaG6Jp8Y2rA2sUppakecfJKC

**Comment by gmale** [comment]
Merged in the content form #212

**Comment by herou** [comment]
Is this solved?

**Comment by gmale** [comment]
No, I just went through all the open issues today and did a little cleanup. Another issue was a duplicate of this so I closed the other one (issue 212).

**Comment by nighthawk24** [comment]
@mandeepbhalothia is on this
