### ISSUE TITLE
Unable to set wallet birthday when restoring a wallet created after 1 millionth block

### ISSUE THREAD

**Issue by nighthawk24** [zcash/zcash-android-wallet#209]
The birthday wallet field only accept 6 digits of block height, making it impossible to enter a 7 digit wallet birthday for wallets created after 1,000,000 blocks.
Expected: The user should be able to enter the 7 digit wallet birthday height.

 - Android Device: Essential PH-1
 - Android Version 11

1. Create a new wallet & backup the seed words
2. Delete the wallet app
3. Try to restore the seed and enter the wallet birthday.

**Comment by gmale** [comment]
Could not reproduce with the latest version of the wallet `1.1.0-alpha37` 

@nighthawk24 which version are you seeing this on?

**Comment by gmale** [comment]
good catch! Addressed in https://github.com/zcash/zcash-android-wallet/pull/211

I'll test and confirm this, shortly.

**Comment by gmale** [comment]
Should be fixed, can be reopened if not.
