### ISSUE TITLE
Wallets are crashing on first launch, probably from an upgrade issue

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#213]
This corresponds to t[his crash in bugsnag](https://app.bugsnag.com/electric-coin-company/ecc-wallet/errors/5f8625522568af00186ca26d?filters[event.since][0]=30d&filters[error.status][0]=open) with the message:

> Expected a viewingKey for this wallet but failed to find one. This usually means that wallet setup happened incorrectly. A workaround might be to derive the viewingKey from the seed or seedPhrase, if they exist, but it is probably better not to mask this error because the root issue should be addressed.

**Comment by gmale** [comment]
Could not reproduce.

So I was not able to pinpoint the exact root cause here although I have a hunch that it's an upgrade issue that's no longer a problem. Since losing the ability to access funds is a very painful problem, I've put in a fallback to load the seed in these cases and derive the keys from there. I've also added troubleshooting code in this area so that if it does occur again I'll be able to diagnose the exact reason why.

I put in a note to remove this code if we go a few releases without seeing the problem crop up again.

**Comment by braddmiller** [comment]
This appears fixed, if it crops up again we will reopen.
