### ISSUE TITLE
Autoshielding Final Designs

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#216]
Upload the final designs for the first implementation of t-address receiving and autoshielding of funds

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/2b8f2f0e-94b9-4f0c-aed0-69b4139f64b2)

**Comment by geffenz** [comment]
Stopgap implementation: ![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/f9998d97-6425-4aab-9cd5-613497a0b206)
