### ISSUE TITLE
Enhancement: Add option to view the error message during a failed send

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#233]
As a user, I'd like to have the option to view details about why sending failed so that I can report more information when troubleshooting a problem.

Update Apr. 5th:
### Design notes
- The intention here is to provide a way for the user to have the **option** to view more details
- This can be accomplished with a 'more info' button or something similar
  - when tapped, it would provide more details on the error
  - given that the ECC app is internal only, it's probably okay to surface the error message as-is
  - otherwise (on nighthawk) a layer of sanitation should be applied to simplify the error for users

### Implementation notes
- the `errorMessage` column in the pendingTransaction database is all that we need to show
- the UiModel currently does not hold that information but that could be added with an `errorDescription` field
- In code, that means change this:
```kotlin
isFailure() -> {
    model.title = getString(R.string.send_final_button_primary_failed)
    model.errorMessage = if (isFailedEncoding()) getString(R.string.send_final_error_encoding) else getString(
                        R.string.send_final_error_submitting)
    model.primaryButtonText = getString(R.string.send_final_button_primary_retry)
    model.primaryAction = { onReturnToSend() }
}
```
to this:
```kotlin
            isFailure() -> {
                model.title = getString(R.string.send_final_button_primary_failed)
                model.errorMessage = if (isFailedEncoding()) getString(R.string.send_final_error_encoding) else getString(
                                    R.string.send_final_error_submitting)
                model.errorDescription = errorMessage
                model.primaryButtonText = getString(R.string.send_final_button_primary_retry)
                model.primaryAction = { onReturnToSend() }
            }
```
- from there, additional work would need to be done to get this message to show up, only when the user taps `more info`
- this can either be scrollable text or a popup. Personally, I'd rather not do a popup.

### Testing notes
- this can be tested most simply by switching to airplane mode after a transaction gets created
   - it takes about 8-10 seconds to build a transaction on device
   - during that time, simply switch to airplane mode to generate a submission error
- a better way to test this would be with a unit test but the code would need to be refactored a little to be more testable
- suggestion: move the existing `toUiModel` code into a testable class, then simply test that class in a unit test
  - that would mean change this inside of `SendFinalFragment`:
  ```kotlin
   private fun PendingTransaction.toUiModel()
  ```
    - to this:
  ```kotlin
   // note this class already exists at the bottom
   data class UiModel(...) {
     fun from(tx: PendingTransaction) { ... }
   }
  ```

**Comment by gmale** [comment]
We just need to surface the [errorMessage](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/src/main/java/cash/z/ecc/android/sdk/db/entity/Transactions.kt#L88) property.

**Comment by nighthawk24** [comment]
@mandeepbhalothia is on this

**Comment by Mandeepbhalothia** [comment]
@gmale Is there any way to test this issue?

**Comment by gmale** [comment]
Added as many notes as I could think of on implementation and testing.
Let me know if that is helpful or if you have further questions.

However, this issue was being worked by @herou so we should pause and sync before moving forward to make sure we're not duplicating efforts.

**Comment by geffenz** [comment]
We actually have a redundant close button here, so we can use the secondary call to action for more info. This should make the changes to this screen minimal.
See below:

![image](https://user-images.githubusercontent.com/47196503/113770498-0c188280-96d7-11eb-902f-dee3e198f425.png)

**Comment by gmale** [comment]
Completed by https://github.com/zcash/zcash-android-wallet/pull/250
