### ISSUE TITLE
Implement t-address display in ECC wallet

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#234]
Implement t-address display in the ecc wallet
- [ ] Tabbed address switch
- [ ] QR Code display
- [ ] Segmented address
- [ ] Language about "receive only" address
- [ ] Share button

- [ ] This displays a real address

**Comment by gmale** [comment]
![29254AA4-C3E8-42E3-B42E-C1AE39BC54A5](https://user-images.githubusercontent.com/1699841/115962325-c4706400-a4e8-11eb-992b-2399864ac4e5.png)

**Comment by gmale** [comment]
@herou I've attached a screenshot of the designs to this issue. We can discuss any questions you have in Signal.

**Comment by gmale** [comment]
This issue is just for the UI work.

**Implementation notes:**
- Modify ReceiveFragment and fragment_receive.xml
- Add tabs and a view pager
- For showing the address, we can borrow the code and UI from the Easter Egg (AwesomeFragment.kt)

**Comment by gmale** [comment]
Completed as part of https://github.com/zcash/zcash-android-wallet/pull/268

**Comment by gmale** [comment]
Missing the "Receive Only" piece but that can be spun out into a separate ticket.
