### ISSUE TITLE
Payment Entry Point UI Redesign (wireframes)

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#237]
Home payment entry point screen criteria:
- [x] The home screen itself which provides access to the following user flows
- [x] Request ZEC (ZIP321)
- - [x] Screen to create a ZIP 321 style payment URI
- [x] Send ZEC (requires the ability to send any or requested amount)
- - [x] Scan entry point (respond to 321)
- - [x] blank amount/scan address entry point
- [x] Receive ZEC (Address)
- - [x] Display address

**Comment by nighthawk24** [comment]
Is it possible to view the design files to estimate the scope of changes?

**Comment by geffenz** [comment]
I'm working on a "mvp" version as well as an ideal version, so short answer - not yet. However, I'll post two sets soon (sometime next sprint).

**Comment by geffenz** [comment]
> Is it possible to view the design files to estimate the scope of changes?

This should be possible next week. Matt let's meet!

@nighthawk24
