### ISSUE TITLE
Update wallet history to match latest designs

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#246]
The wallet history designs have been refreshed for quite some time and iOS has the newer style. Android is behind. This ticket is for implementing the latest and greatest version of history.

Criteria:
- The UI matches the designs

**Comment by gmale** [comment]
Note for context: the current designs are on the left, the more recent designs are on the right. We still need to finalize the exact requirements of the new design but this is just to give an idea:

<img src="https://user-images.githubusercontent.com/1699841/114223988-7bdc7680-993e-11eb-9adb-1bedba0d059d.png" width=340/> <img src="https://user-images.githubusercontent.com/1699841/114223998-80a12a80-993e-11eb-995d-9abe3b278138.png" width=340/>

**Comment by gmale** [comment]
TODO: Assign this to @Mandeepbhalothia

**Comment by Mandeepbhalothia** [comment]
@gmale I have few doubts regarding to new UI:

1. Should all pending transaction be on top?
2. Light yellow line on the top of first element, Is this for every pending transaction or for only any type(including receiving/sending) first element?

**Comment by gmale** [comment]
Great questions! I had a call with Adi yesterday and we chatted about this in detail. I'll add and some of that info here:

- First, to address your question, we should avoid complexity and keep these changes as simple as possible
- that means we shouldn't add any new logic for grouping
- transactions are sorted by time so most pending transactions will already be at or near the top. So that's sufficient.
- let's skip the extra info for pending transactions, for now (confirmations and change) because the data doesn't give us change info just yet
- ideally, these tickets would be greatly detailed and ready for work but unfortunately we are probably spread too thin to achieve that anytime soon
- please feel free to ask clarifying questions as often as you like!

Note there are also a lot of pending changes coming in the SDK and wallet. All SDK changes are committed but not merged because we ran into a show stopper bug. For the wallet, I'll try to get those at least into a branch on Monday.
