### ISSUE TITLE
Add ktlint to the wallet

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#247]
This ticket is to do similar work on the wallet as was done on the SDK to incorporate ktlint
https://github.com/zcash/zcash-android-wallet-sdk/issues/185

Since this will touch a lot of files, it should probably happen after the current wave of changes are merged to master (hopefully, that would be early next week)

@nighthawk24 has asked to pick this up. I'll assign it once the github team work is complete by @mdr0id 
Update: @nighthawk24 has been added to the github group. Invite pending.

**Comment by nighthawk24** [comment]
PR is up for review https://github.com/zcash/zcash-android-wallet/pull/248
