### ISSUE TITLE
Display Balance Details UI (t-address)

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#86]
On the home screen, there is a balance detail screen that can pop up to show the difference in z-address balance and t-address balance. This should match the designs provided.

**Edit**:
We are going to implement this before t-addresses are available, new intermediate design is incoming.

**Comment by gmale** [comment]
Open question:

This could be a good opportunity to show the pending v. available funds. We do that a bit at the bottom but it feels like we could flesh it out more. For instance, it's currently very unclear what text will go in the footer for all the possible cases.

Perhaps this is a symptom of a root issue: we could more clearly show the balance breakdown across T/Z and Available/Pending.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/0045250a-82eb-4230-ae49-a5544f389e9f)

7/23 small update - we are sacrificing the modal feel to add a more information button for first iteration.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/6df50b18-4964-4bc3-91e5-ad3a42b1275c)

Interim layout.

**Comment by gmale** [comment]
This is changing as part of autoshielding. We can close this ticket in favor of the newer work and reopen it, if needed.
